//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEmployeeAssignment.LoginService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginUser", ReplyAction="http://tempuri.org/ILoginService/LoginUserResponse")]
        ProjectEmployeeAssignment.LoginService.LoginUserResponse LoginUser(ProjectEmployeeAssignment.LoginService.LoginUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/LoginUser", ReplyAction="http://tempuri.org/ILoginService/LoginUserResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.LoginService.LoginUserResponse> LoginUserAsync(ProjectEmployeeAssignment.LoginService.LoginUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SaveOperationLog", ReplyAction="http://tempuri.org/ILoginService/SaveOperationLogResponse")]
        ProjectEmployeeAssignment.LoginService.SaveOperationLogResponse SaveOperationLog(ProjectEmployeeAssignment.LoginService.SaveOperationLogRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/SaveOperationLog", ReplyAction="http://tempuri.org/ILoginService/SaveOperationLogResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.LoginService.SaveOperationLogResponse> SaveOperationLogAsync(ProjectEmployeeAssignment.LoginService.SaveOperationLogRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string hash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public PEA_Common.SessionUserModel user;
        
        public LoginUserRequest() {
        }
        
        public LoginUserRequest(string hash, string returnMessage, PEA_Common.SessionUserModel user) {
            this.hash = hash;
            this.returnMessage = returnMessage;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class LoginUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool LoginUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public PEA_Common.SessionUserModel user;
        
        public LoginUserResponse() {
        }
        
        public LoginUserResponse(bool LoginUserResult, string returnMessage, PEA_Common.SessionUserModel user) {
            this.LoginUserResult = LoginUserResult;
            this.returnMessage = returnMessage;
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveOperationLog", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveOperationLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PEA_Common.OperationModel operationModel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        public SaveOperationLogRequest() {
        }
        
        public SaveOperationLogRequest(PEA_Common.OperationModel operationModel, string returnMessage) {
            this.operationModel = operationModel;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveOperationLogResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveOperationLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool SaveOperationLogResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        public SaveOperationLogResponse() {
        }
        
        public SaveOperationLogResponse(bool SaveOperationLogResult, string returnMessage) {
            this.SaveOperationLogResult = SaveOperationLogResult;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : ProjectEmployeeAssignment.LoginService.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<ProjectEmployeeAssignment.LoginService.ILoginService>, ProjectEmployeeAssignment.LoginService.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.LoginService.LoginUserResponse ProjectEmployeeAssignment.LoginService.ILoginService.LoginUser(ProjectEmployeeAssignment.LoginService.LoginUserRequest request) {
            return base.Channel.LoginUser(request);
        }
        
        public bool LoginUser(string hash, ref string returnMessage, ref PEA_Common.SessionUserModel user) {
            ProjectEmployeeAssignment.LoginService.LoginUserRequest inValue = new ProjectEmployeeAssignment.LoginService.LoginUserRequest();
            inValue.hash = hash;
            inValue.returnMessage = returnMessage;
            inValue.user = user;
            ProjectEmployeeAssignment.LoginService.LoginUserResponse retVal = ((ProjectEmployeeAssignment.LoginService.ILoginService)(this)).LoginUser(inValue);
            returnMessage = retVal.returnMessage;
            user = retVal.user;
            return retVal.LoginUserResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.LoginService.LoginUserResponse> LoginUserAsync(ProjectEmployeeAssignment.LoginService.LoginUserRequest request) {
            return base.Channel.LoginUserAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.LoginService.SaveOperationLogResponse ProjectEmployeeAssignment.LoginService.ILoginService.SaveOperationLog(ProjectEmployeeAssignment.LoginService.SaveOperationLogRequest request) {
            return base.Channel.SaveOperationLog(request);
        }
        
        public bool SaveOperationLog(PEA_Common.OperationModel operationModel, ref string returnMessage) {
            ProjectEmployeeAssignment.LoginService.SaveOperationLogRequest inValue = new ProjectEmployeeAssignment.LoginService.SaveOperationLogRequest();
            inValue.operationModel = operationModel;
            inValue.returnMessage = returnMessage;
            ProjectEmployeeAssignment.LoginService.SaveOperationLogResponse retVal = ((ProjectEmployeeAssignment.LoginService.ILoginService)(this)).SaveOperationLog(inValue);
            returnMessage = retVal.returnMessage;
            return retVal.SaveOperationLogResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.LoginService.SaveOperationLogResponse> SaveOperationLogAsync(ProjectEmployeeAssignment.LoginService.SaveOperationLogRequest request) {
            return base.Channel.SaveOperationLogAsync(request);
        }
    }
}
