//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEmployeeAssignment.DepartmentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DepartmentService.IDepartmentService")]
    public interface IDepartmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartmentList", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentListResponse")]
        ProjectEmployeeAssignment.DepartmentService.GetDepartmentListResponse GetDepartmentList(ProjectEmployeeAssignment.DepartmentService.GetDepartmentListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDepartmentService/GetDepartmentList", ReplyAction="http://tempuri.org/IDepartmentService/GetDepartmentListResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.DepartmentService.GetDepartmentListResponse> GetDepartmentListAsync(ProjectEmployeeAssignment.DepartmentService.GetDepartmentListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartmentList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDepartmentListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PEA_Common.DepartmentModel[] departmentList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        public GetDepartmentListRequest() {
        }
        
        public GetDepartmentListRequest(PEA_Common.DepartmentModel[] departmentList, string returnMessage) {
            this.departmentList = departmentList;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDepartmentListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDepartmentListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetDepartmentListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public PEA_Common.DepartmentModel[] departmentList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string returnMessage;
        
        public GetDepartmentListResponse() {
        }
        
        public GetDepartmentListResponse(bool GetDepartmentListResult, PEA_Common.DepartmentModel[] departmentList, string returnMessage) {
            this.GetDepartmentListResult = GetDepartmentListResult;
            this.departmentList = departmentList;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDepartmentServiceChannel : ProjectEmployeeAssignment.DepartmentService.IDepartmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DepartmentServiceClient : System.ServiceModel.ClientBase<ProjectEmployeeAssignment.DepartmentService.IDepartmentService>, ProjectEmployeeAssignment.DepartmentService.IDepartmentService {
        
        public DepartmentServiceClient() {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DepartmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.DepartmentService.GetDepartmentListResponse ProjectEmployeeAssignment.DepartmentService.IDepartmentService.GetDepartmentList(ProjectEmployeeAssignment.DepartmentService.GetDepartmentListRequest request) {
            return base.Channel.GetDepartmentList(request);
        }
        
        public bool GetDepartmentList(ref PEA_Common.DepartmentModel[] departmentList, ref string returnMessage) {
            ProjectEmployeeAssignment.DepartmentService.GetDepartmentListRequest inValue = new ProjectEmployeeAssignment.DepartmentService.GetDepartmentListRequest();
            inValue.departmentList = departmentList;
            inValue.returnMessage = returnMessage;
            ProjectEmployeeAssignment.DepartmentService.GetDepartmentListResponse retVal = ((ProjectEmployeeAssignment.DepartmentService.IDepartmentService)(this)).GetDepartmentList(inValue);
            departmentList = retVal.departmentList;
            returnMessage = retVal.returnMessage;
            return retVal.GetDepartmentListResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.DepartmentService.GetDepartmentListResponse> GetDepartmentListAsync(ProjectEmployeeAssignment.DepartmentService.GetDepartmentListRequest request) {
            return base.Channel.GetDepartmentListAsync(request);
        }
    }
}
