//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEmployeeAssignment.EmployeeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.IEmployeeService")]
    public interface IEmployeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeCreate", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeCreateResponse")]
        ProjectEmployeeAssignment.EmployeeService.EmployeeCreateResponse EmployeeCreate(ProjectEmployeeAssignment.EmployeeService.EmployeeCreateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeCreate", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeCreateResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.EmployeeCreateResponse> EmployeeCreateAsync(ProjectEmployeeAssignment.EmployeeService.EmployeeCreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeList", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeListResponse")]
        ProjectEmployeeAssignment.EmployeeService.GetEmployeeListResponse GetEmployeeList(ProjectEmployeeAssignment.EmployeeService.GetEmployeeListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeList", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeListResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.GetEmployeeListResponse> GetEmployeeListAsync(ProjectEmployeeAssignment.EmployeeService.GetEmployeeListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeUpdate", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeUpdateResponse")]
        ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateResponse EmployeeUpdate(ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeUpdate", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeUpdateResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateResponse> EmployeeUpdateAsync(ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIdResponse")]
        ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdResponse GetEmployeeById(ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetEmployeeById", ReplyAction="http://tempuri.org/IEmployeeService/GetEmployeeByIdResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdResponse> GetEmployeeByIdAsync(ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeDelete", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeDeleteResponse")]
        ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteResponse EmployeeDelete(ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/EmployeeDelete", ReplyAction="http://tempuri.org/IEmployeeService/EmployeeDeleteResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteResponse> EmployeeDeleteAsync(ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllDataCount", ReplyAction="http://tempuri.org/IEmployeeService/GetAllDataCountResponse")]
        ProjectEmployeeAssignment.EmployeeService.GetAllDataCountResponse GetAllDataCount(ProjectEmployeeAssignment.EmployeeService.GetAllDataCountRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmployeeService/GetAllDataCount", ReplyAction="http://tempuri.org/IEmployeeService/GetAllDataCountResponse")]
        System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.GetAllDataCountResponse> GetAllDataCountAsync(ProjectEmployeeAssignment.EmployeeService.GetAllDataCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeCreate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmployeeCreateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PEA_Common.EMPModel empModel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ret;
        
        public EmployeeCreateRequest() {
        }
        
        public EmployeeCreateRequest(PEA_Common.EMPModel empModel, string ret) {
            this.empModel = empModel;
            this.ret = ret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeCreateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmployeeCreateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool EmployeeCreateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ret;
        
        public EmployeeCreateResponse() {
        }
        
        public EmployeeCreateResponse(bool EmployeeCreateResult, string ret) {
            this.EmployeeCreateResult = EmployeeCreateResult;
            this.ret = ret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PEA_Common.EMPModel[] empList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ret;
        
        public GetEmployeeListRequest() {
        }
        
        public GetEmployeeListRequest(PEA_Common.EMPModel[] empList, string ret) {
            this.empList = empList;
            this.ret = ret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetEmployeeListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public PEA_Common.EMPModel[] empList;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ret;
        
        public GetEmployeeListResponse() {
        }
        
        public GetEmployeeListResponse(bool GetEmployeeListResult, PEA_Common.EMPModel[] empList, string ret) {
            this.GetEmployeeListResult = GetEmployeeListResult;
            this.empList = empList;
            this.ret = ret;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeUpdate", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmployeeUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public PEA_Common.EMPModel empModel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        public EmployeeUpdateRequest() {
        }
        
        public EmployeeUpdateRequest(PEA_Common.EMPModel empModel, string returnMessage) {
            this.empModel = empModel;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeUpdateResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmployeeUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool EmployeeUpdateResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        public EmployeeUpdateResponse() {
        }
        
        public EmployeeUpdateResponse(bool EmployeeUpdateResult, string returnMessage) {
            this.EmployeeUpdateResult = EmployeeUpdateResult;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeById", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Guid id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public PEA_Common.UpdateEMPTModel empt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string returnMessage;
        
        public GetEmployeeByIdRequest() {
        }
        
        public GetEmployeeByIdRequest(System.Guid id, PEA_Common.UpdateEMPTModel empt, string returnMessage) {
            this.id = id;
            this.empt = empt;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmployeeByIdResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmployeeByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetEmployeeByIdResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public PEA_Common.UpdateEMPTModel empt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string returnMessage;
        
        public GetEmployeeByIdResponse() {
        }
        
        public GetEmployeeByIdResponse(bool GetEmployeeByIdResult, PEA_Common.UpdateEMPTModel empt, string returnMessage) {
            this.GetEmployeeByIdResult = GetEmployeeByIdResult;
            this.empt = empt;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeDelete", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmployeeDeleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int userId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] EMT_ID_LIST;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string returnMessage;
        
        public EmployeeDeleteRequest() {
        }
        
        public EmployeeDeleteRequest(int userId, string[] EMT_ID_LIST, string returnMessage) {
            this.userId = userId;
            this.EMT_ID_LIST = EMT_ID_LIST;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="EmployeeDeleteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class EmployeeDeleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool EmployeeDeleteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string returnMessage;
        
        public EmployeeDeleteResponse() {
        }
        
        public EmployeeDeleteResponse(bool EmployeeDeleteResult, string returnMessage) {
            this.EmployeeDeleteResult = EmployeeDeleteResult;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllDataCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllDataCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int activeCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int inactiveCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string returnMessage;
        
        public GetAllDataCountRequest() {
        }
        
        public GetAllDataCountRequest(int activeCount, int inactiveCount, string returnMessage) {
            this.activeCount = activeCount;
            this.inactiveCount = inactiveCount;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllDataCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAllDataCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GetAllDataCountResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int activeCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int inactiveCount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string returnMessage;
        
        public GetAllDataCountResponse() {
        }
        
        public GetAllDataCountResponse(bool GetAllDataCountResult, int activeCount, int inactiveCount, string returnMessage) {
            this.GetAllDataCountResult = GetAllDataCountResult;
            this.activeCount = activeCount;
            this.inactiveCount = inactiveCount;
            this.returnMessage = returnMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmployeeServiceChannel : ProjectEmployeeAssignment.EmployeeService.IEmployeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeServiceClient : System.ServiceModel.ClientBase<ProjectEmployeeAssignment.EmployeeService.IEmployeeService>, ProjectEmployeeAssignment.EmployeeService.IEmployeeService {
        
        public EmployeeServiceClient() {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.EmployeeService.EmployeeCreateResponse ProjectEmployeeAssignment.EmployeeService.IEmployeeService.EmployeeCreate(ProjectEmployeeAssignment.EmployeeService.EmployeeCreateRequest request) {
            return base.Channel.EmployeeCreate(request);
        }
        
        public bool EmployeeCreate(PEA_Common.EMPModel empModel, ref string ret) {
            ProjectEmployeeAssignment.EmployeeService.EmployeeCreateRequest inValue = new ProjectEmployeeAssignment.EmployeeService.EmployeeCreateRequest();
            inValue.empModel = empModel;
            inValue.ret = ret;
            ProjectEmployeeAssignment.EmployeeService.EmployeeCreateResponse retVal = ((ProjectEmployeeAssignment.EmployeeService.IEmployeeService)(this)).EmployeeCreate(inValue);
            ret = retVal.ret;
            return retVal.EmployeeCreateResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.EmployeeCreateResponse> EmployeeCreateAsync(ProjectEmployeeAssignment.EmployeeService.EmployeeCreateRequest request) {
            return base.Channel.EmployeeCreateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.EmployeeService.GetEmployeeListResponse ProjectEmployeeAssignment.EmployeeService.IEmployeeService.GetEmployeeList(ProjectEmployeeAssignment.EmployeeService.GetEmployeeListRequest request) {
            return base.Channel.GetEmployeeList(request);
        }
        
        public bool GetEmployeeList(ref PEA_Common.EMPModel[] empList, ref string ret) {
            ProjectEmployeeAssignment.EmployeeService.GetEmployeeListRequest inValue = new ProjectEmployeeAssignment.EmployeeService.GetEmployeeListRequest();
            inValue.empList = empList;
            inValue.ret = ret;
            ProjectEmployeeAssignment.EmployeeService.GetEmployeeListResponse retVal = ((ProjectEmployeeAssignment.EmployeeService.IEmployeeService)(this)).GetEmployeeList(inValue);
            empList = retVal.empList;
            ret = retVal.ret;
            return retVal.GetEmployeeListResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.GetEmployeeListResponse> GetEmployeeListAsync(ProjectEmployeeAssignment.EmployeeService.GetEmployeeListRequest request) {
            return base.Channel.GetEmployeeListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateResponse ProjectEmployeeAssignment.EmployeeService.IEmployeeService.EmployeeUpdate(ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateRequest request) {
            return base.Channel.EmployeeUpdate(request);
        }
        
        public bool EmployeeUpdate(PEA_Common.EMPModel empModel, ref string returnMessage) {
            ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateRequest inValue = new ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateRequest();
            inValue.empModel = empModel;
            inValue.returnMessage = returnMessage;
            ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateResponse retVal = ((ProjectEmployeeAssignment.EmployeeService.IEmployeeService)(this)).EmployeeUpdate(inValue);
            returnMessage = retVal.returnMessage;
            return retVal.EmployeeUpdateResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateResponse> EmployeeUpdateAsync(ProjectEmployeeAssignment.EmployeeService.EmployeeUpdateRequest request) {
            return base.Channel.EmployeeUpdateAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdResponse ProjectEmployeeAssignment.EmployeeService.IEmployeeService.GetEmployeeById(ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdRequest request) {
            return base.Channel.GetEmployeeById(request);
        }
        
        public bool GetEmployeeById(System.Guid id, ref PEA_Common.UpdateEMPTModel empt, ref string returnMessage) {
            ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdRequest inValue = new ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdRequest();
            inValue.id = id;
            inValue.empt = empt;
            inValue.returnMessage = returnMessage;
            ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdResponse retVal = ((ProjectEmployeeAssignment.EmployeeService.IEmployeeService)(this)).GetEmployeeById(inValue);
            empt = retVal.empt;
            returnMessage = retVal.returnMessage;
            return retVal.GetEmployeeByIdResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdResponse> GetEmployeeByIdAsync(ProjectEmployeeAssignment.EmployeeService.GetEmployeeByIdRequest request) {
            return base.Channel.GetEmployeeByIdAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteResponse ProjectEmployeeAssignment.EmployeeService.IEmployeeService.EmployeeDelete(ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteRequest request) {
            return base.Channel.EmployeeDelete(request);
        }
        
        public bool EmployeeDelete(int userId, string[] EMT_ID_LIST, ref string returnMessage) {
            ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteRequest inValue = new ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteRequest();
            inValue.userId = userId;
            inValue.EMT_ID_LIST = EMT_ID_LIST;
            inValue.returnMessage = returnMessage;
            ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteResponse retVal = ((ProjectEmployeeAssignment.EmployeeService.IEmployeeService)(this)).EmployeeDelete(inValue);
            returnMessage = retVal.returnMessage;
            return retVal.EmployeeDeleteResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteResponse> EmployeeDeleteAsync(ProjectEmployeeAssignment.EmployeeService.EmployeeDeleteRequest request) {
            return base.Channel.EmployeeDeleteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectEmployeeAssignment.EmployeeService.GetAllDataCountResponse ProjectEmployeeAssignment.EmployeeService.IEmployeeService.GetAllDataCount(ProjectEmployeeAssignment.EmployeeService.GetAllDataCountRequest request) {
            return base.Channel.GetAllDataCount(request);
        }
        
        public bool GetAllDataCount(ref int activeCount, ref int inactiveCount, ref string returnMessage) {
            ProjectEmployeeAssignment.EmployeeService.GetAllDataCountRequest inValue = new ProjectEmployeeAssignment.EmployeeService.GetAllDataCountRequest();
            inValue.activeCount = activeCount;
            inValue.inactiveCount = inactiveCount;
            inValue.returnMessage = returnMessage;
            ProjectEmployeeAssignment.EmployeeService.GetAllDataCountResponse retVal = ((ProjectEmployeeAssignment.EmployeeService.IEmployeeService)(this)).GetAllDataCount(inValue);
            activeCount = retVal.activeCount;
            inactiveCount = retVal.inactiveCount;
            returnMessage = retVal.returnMessage;
            return retVal.GetAllDataCountResult;
        }
        
        public System.Threading.Tasks.Task<ProjectEmployeeAssignment.EmployeeService.GetAllDataCountResponse> GetAllDataCountAsync(ProjectEmployeeAssignment.EmployeeService.GetAllDataCountRequest request) {
            return base.Channel.GetAllDataCountAsync(request);
        }
    }
}
