//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEA_Common
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PEAEntities : DbContext
    {
        public PEAEntities()
            : base("name=PEAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_Department> TB_Department { get; set; }
        public virtual DbSet<TB_Employee> TB_Employee { get; set; }
        public virtual DbSet<TB_OperationLog> TB_OperationLog { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
