//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEA_Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_OperationLog
    {
        public int OperationLogSeq { get; set; }
        public System.DateTime OperationDatetime { get; set; }
        public string UserId { get; set; }
        public string CookieUserId { get; set; }
        public string Url { get; set; }
        public string ActionName { get; set; }
        public string ActionParameter { get; set; }
        public string RemoteAddress { get; set; }
        public string RemoteHost { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
